### ISSUE TITLE
Set up a basic website that the team can work from

### ISSUE THREAD

**Issue by jake-bickle** [cs-510-explorations-car-dependence/cs-510-explorations-car-dependence.github.io#1]
Acceptance criteria
- Basic website with essentially nothing on it
- Ready for a basic workflow for our tech stack: Typescript, npm package requirements, can be set up on our organization's Github IO page

**Comment by rattboi** [comment]
Think this is working. Go to https://cs-510-explorations-car-dependence.github.io/ and you'll see our empty react site.

We get new deployment on merge to main, and you can only merge to main on these conditions:
* Passes tests
* Successfully builds
* 1 Approving Review from a team member

**Comment by rattboi** [comment]
test
