### ISSUE TITLE
Create a simple Flask webserver

### ISSUE THREAD

**Issue by jake-bickle** [cs-510-explorations-car-dependence/cs-510-explorations-car-dependence.github.io#15]
Might have to use Google Cloud Credits for this one.

Acceptance criteria
- Our current webpages are supplied by Python's Flask web server
- Merging code into the main branch automatically updates the web server

**Comment by rattboi** [comment]
I'm not sure this is quite the architecture I was expecting. I believe we'll want to host and serve the frontend from github pages (as it is), and have a backend service that the frontend can reach out to for various tasks, and to hide sensitive data from the frontend, like the API keys.

**Comment by rattboi** [comment]
I just created the [backend repo](https://github.com/cs-510-explorations-car-dependence/backend) and put some automation in place to automatically deploy to Heroku, as it was easier than setting up the same in GCP.

**Comment by rattboi** [comment]
you can see the results [here](https://car-dependence-backend.herokuapp.com/)

I'm gonna say this is done. We can re-open if anyone disagrees.
