### ISSUE TITLE
Create a map data schema for interacting between client and webserver

### ISSUE THREAD

**Issue by jake-bickle** [cs-510-explorations-car-dependence/cs-510-explorations-car-dependence.github.io#16]
We need to develop a data schema that provides all necessary information to provide emission data for any arbitrary point on the map (if any is available).

Acceptance criteria
- At no point is any API key sent to the client
- Allows mapping modeled emission data over a road
- Describes what emission data is modeled to which roads
- Can be sent reasonably fast over the network (No insane downloads of greater than 50 MB)
- Could potentially respond in errors, reporting that we have reached our limit to the API usage in ticket #2

**Comment by jake-bickle** [comment]
Matt mentioned to me something like 
```
...
{
  "emissions": ?, // whatever emission data
  "linePath": [[<lon0>, <lat0>], [<lon1>, <lat1>], ...] // points on the road
},
...
```
would be a good start. This would imply that emission data extends the entire length of a road. This would be problematic for large roads such as interstates. Possibly chopping a road up into pairs of segments would be more accurate.

**Comment by jake-bickle** [comment]
Client will send a request to the RESTful endpoint containing two coordinate pairs representing a bounding box of the roads they want information about.
I don't have the details of how the client will do this yet, but probably as query parameters in an HTTP URL request.

Upon success, HTTP code 200 is returned with the following proposed JSON:
```
[
	{
		"road": "road_name_here"
		"segments": [
			{
				"NOx": 0,   # Don't have units for these emitted particles yet.
				"VOC": 0,
				"PM2.5": 0,
				"PM10": 0,
				"CO2": 0,
				"shape": [
					[lat,long]
					...
				]
			}
			...
		]
	}
	...
]
```

If for some reason we are unable to perform the request, such as being rate limited by HERE, HTTP code 503 is returned with no further information.
As always, if an error occurs on the server, HTTP 500 is returned.

**Comment by Tattomoosa** [comment]
This looks good to me

**Comment by jake-bickle** [comment]
The client will perform the request by navigating to "/api/bbox?ul=45.000000,-130.000000&br=44.0000000,-129.000000"

ul = Upper left (north west) boundary of the bounding box. br = Bottom right (south east) boundary of the bounding box. 
Coordinate format is `latitude,longitude`. No spaces. 
The significant digits doesn't matter. 
We will need to limit the size of the bounding box to prevent too much data from being requested. We will need to do some testing to figure out which limit is reasonable.

May return a 400 if 
- The query format is incorrect  (Name: "invalid_syntax")
- Any latitude is not >= -90 or <= 90   (Name: "invalid_coordinates")
- Any longitude is not >= -180 or <= 180 (Name: "invalid_coordinates")
- (In the future) The bounding box is too large (Name: "bbox_too_large")

and return the following JSON
```
{
    name: "A name of the error for programmatic access"
    description: "Description of error"
}
```
