### ISSUE TITLE
Webpage accesses RESTful API when necessary

### ISSUE THREAD

**Issue by jake-bickle** [cs-510-explorations-car-dependence/cs-510-explorations-car-dependence.github.io#18]
This will likely be a difficult ticket that multiple people need to collaborate with and tackle. Will likely want to collaborate with whoever is working on #17 as well.

Acceptance criteria
- As the player scrolls around the map, new requests are made to the web server API 
- Can handle network errors, such as the web server failing to respond
- Can handle errors reported in the server response

**Comment by Tattomoosa** [comment]
Done!
